local M = {
	g = {
		mapleader = " ",
	},
	opts = {
		background = "dark",
		equalalways = true,
		timeout = true,
		timeoutlen = 100,
		foldenable = false,
		foldmethod = "manual",
		foldexpr = "nvim_treesitter#foldexpr()",
		fillchars = "vert:│,eob: ,fold:•",
		listchars = {
			trail = "•",
			extends = "❯",
			precedes = "❮",
			conceal = "⁞",
			tab = "  ",
		},
		hidden = true,
		smarttab = true,
		smartcase = true,
		splitbelow = true,
		clipboard = "unnamedplus",
		cursorline = true,
		termguicolors = true,
		list = true,
		numberwidth = 3,
		undofile = true,
		signcolumn = "yes",
		spell = false,
		updatetime = 250,
		spelllang = "en_us",
		expandtab = true,
		mouse = "a",
		splitright = true,
		autoindent = true,
		smartindent = true,
		completeopt = "menu,menuone,noselect",
		ruler = false,
		number = true,
		softtabstop = 4,
		shiftwidth = 4,
		ignorecase = true,
		swapfile = false,
		tabstop = 4,
		wildmenu = true,
	},
}

return M
